import { PrismaClient, GadgetCategory } from '@prisma/client';

const prisma = new PrismaClient();

const gadgets = [
  // ─── SMARTPHONE ───────────────────────────────────────────────
  // Apple iPhone
  { name: 'iPhone 16', brand: 'Apple', category: 'smartphone' as GadgetCategory, imageUrl: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-black?wid=400&hei=400&fmt=jpeg', specs: { layar: '6.1" Super Retina XDR OLED', prosesor: 'Apple A18', ram: '8GB', storage: '128GB / 256GB / 512GB', kamera_utama: '48MP Fusion + 12MP Ultra Wide', kamera_depan: '12MP TrueDepth', baterai: '3,561 mAh', os: 'iOS 18', konektivitas: '5G, Wi-Fi 7, Bluetooth 5.3', rilis: '2024' } },
  { name: 'iPhone 16 Plus', brand: 'Apple', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" Super Retina XDR OLED', prosesor: 'Apple A18', ram: '8GB', storage: '128GB / 256GB / 512GB', kamera_utama: '48MP Fusion + 12MP Ultra Wide', baterai: '4,674 mAh', os: 'iOS 18', rilis: '2024' } },
  { name: 'iPhone 16 Pro', brand: 'Apple', category: 'smartphone' as GadgetCategory, specs: { layar: '6.3" ProMotion OLED 120Hz', prosesor: 'Apple A18 Pro', ram: '8GB', storage: '128GB / 256GB / 512GB / 1TB', kamera_utama: '48MP Fusion + 48MP Ultra Wide + 12MP 5x Tele', kamera_depan: '12MP TrueDepth', baterai: '3,582 mAh', os: 'iOS 18', konektivitas: '5G, Wi-Fi 7, USB-C 3', rilis: '2024' } },
  { name: 'iPhone 16 Pro Max', brand: 'Apple', category: 'smartphone' as GadgetCategory, specs: { layar: '6.9" ProMotion OLED 120Hz', prosesor: 'Apple A18 Pro', ram: '8GB', storage: '256GB / 512GB / 1TB', kamera_utama: '48MP Fusion + 48MP Ultra Wide + 12MP 5x Tele', baterai: '4,685 mAh', os: 'iOS 18', konektivitas: '5G, Wi-Fi 7, USB-C 3', rilis: '2024' } },
  { name: 'iPhone 17', brand: 'Apple', category: 'smartphone' as GadgetCategory, specs: { layar: '6.1" ProMotion OLED 120Hz', prosesor: 'Apple A19', ram: '8GB', storage: '128GB / 256GB / 512GB', kamera_utama: '48MP Fusion + 12MP Ultra Wide', kamera_depan: '24MP TrueDepth', baterai: '3,600 mAh', os: 'iOS 19', konektivitas: '5G, Wi-Fi 7, Bluetooth 5.4', rilis: '2025' } },
  { name: 'iPhone 17 Air', brand: 'Apple', category: 'smartphone' as GadgetCategory, specs: { layar: '6.6" ProMotion OLED 120Hz', prosesor: 'Apple A19', ram: '8GB', storage: '128GB / 256GB', kamera_utama: '48MP Fusion', ketebalan: '5.5mm (tertipis iPhone)', baterai: '2,800 mAh', os: 'iOS 19', rilis: '2025' } },
  { name: 'iPhone 17 Pro', brand: 'Apple', category: 'smartphone' as GadgetCategory, specs: { layar: '6.3" ProMotion OLED 120Hz', prosesor: 'Apple A19 Pro', ram: '12GB', storage: '256GB / 512GB / 1TB', kamera_utama: '48MP Fusion + 48MP Ultra Wide + 12MP 5x Tele', kamera_depan: '24MP TrueDepth', baterai: '3,700 mAh', os: 'iOS 19', konektivitas: '5G, Wi-Fi 7, USB-C 3', rilis: '2025' } },
  { name: 'iPhone 17 Pro Max', brand: 'Apple', category: 'smartphone' as GadgetCategory, specs: { layar: '6.9" ProMotion OLED 120Hz', prosesor: 'Apple A19 Pro', ram: '12GB', storage: '256GB / 512GB / 1TB', kamera_utama: '48MP Fusion + 48MP Ultra Wide + 12MP 5x Tele', baterai: '4,900 mAh', os: 'iOS 19', konektivitas: '5G, Wi-Fi 7, USB-C 3', rilis: '2025' } },

  // Samsung Galaxy S series
  { name: 'Galaxy S24', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.2" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Gen 3', ram: '8GB', storage: '128GB / 256GB', kamera_utama: '50MP + 12MP + 10MP 3x Tele', kamera_depan: '12MP', baterai: '4,000 mAh', os: 'Android 14 / One UI 6.1', konektivitas: '5G, Wi-Fi 6E', rilis: '2024' } },
  { name: 'Galaxy S24+', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Gen 3', ram: '12GB', storage: '256GB / 512GB', kamera_utama: '50MP + 12MP + 10MP 3x Tele', baterai: '4,900 mAh', os: 'Android 14 / One UI 6.1', rilis: '2024' } },
  { name: 'Galaxy S24 Ultra', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.8" Dynamic AMOLED 2X 120Hz QHD+', prosesor: 'Snapdragon 8 Gen 3', ram: '12GB', storage: '256GB / 512GB / 1TB', kamera_utama: '200MP + 12MP + 10MP 3x + 50MP 5x Tele', kamera_depan: '12MP', baterai: '5,000 mAh', os: 'Android 14 / One UI 6.1', fitur: 'S Pen built-in', rilis: '2024' } },
  { name: 'Galaxy S24 FE', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" Dynamic AMOLED 2X 120Hz', prosesor: 'Exynos 2500', ram: '8GB', storage: '128GB / 256GB', kamera_utama: '50MP + 8MP + 10MP 3x Tele', baterai: '4,700 mAh', os: 'Android 14 / One UI 7', rilis: '2024' } },
  { name: 'Galaxy S25', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.2" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Elite', ram: '12GB', storage: '128GB / 256GB', kamera_utama: '50MP + 12MP + 10MP 3x Tele', kamera_depan: '12MP', baterai: '4,000 mAh', os: 'Android 15 / One UI 7', konektivitas: '5G, Wi-Fi 7', rilis: '2025' } },
  { name: 'Galaxy S25+', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Elite', ram: '12GB', storage: '256GB / 512GB', kamera_utama: '50MP + 12MP + 10MP 3x Tele', baterai: '4,900 mAh', os: 'Android 15 / One UI 7', rilis: '2025' } },
  { name: 'Galaxy S25 Ultra', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.9" Dynamic AMOLED 2X 120Hz QHD+', prosesor: 'Snapdragon 8 Elite', ram: '12GB', storage: '256GB / 512GB / 1TB', kamera_utama: '200MP + 50MP + 10MP 3x + 50MP 5x Tele', kamera_depan: '12MP', baterai: '5,000 mAh', os: 'Android 15 / One UI 7', fitur: 'S Pen built-in', rilis: '2025' } },
  { name: 'Galaxy S25 Edge', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Elite', ram: '12GB', storage: '256GB', kamera_utama: '200MP + 12MP Ultra Wide', ketebalan: '5.8mm', baterai: '3,900 mAh', os: 'Android 15 / One UI 7', rilis: '2025' } },
  { name: 'Galaxy Z Fold 6', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar_dalam: '7.6" Dynamic AMOLED 2X 120Hz', layar_luar: '6.3" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Gen 3', ram: '12GB', storage: '256GB / 512GB / 1TB', kamera_utama: '50MP + 12MP + 10MP 3x Tele', baterai: '4,400 mAh', os: 'Android 14 / One UI 6.1.1', rilis: '2024' } },
  { name: 'Galaxy Z Flip 6', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" Dynamic AMOLED 2X 120Hz (lipat)', layar_luar: '3.4" Super AMOLED', prosesor: 'Snapdragon 8 Gen 3', ram: '12GB', storage: '256GB / 512GB', kamera_utama: '50MP + 12MP Ultra Wide', baterai: '4,000 mAh', os: 'Android 14 / One UI 6.1.1', rilis: '2024' } },
  { name: 'Galaxy A55 5G', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.6" Super AMOLED 120Hz', prosesor: 'Exynos 1480', ram: '8GB', storage: '128GB / 256GB', kamera_utama: '50MP + 12MP + 5MP', kamera_depan: '32MP', baterai: '5,000 mAh', os: 'Android 14 / One UI 6.1', rilis: '2024' } },
  { name: 'Galaxy A35 5G', brand: 'Samsung', category: 'smartphone' as GadgetCategory, specs: { layar: '6.6" Super AMOLED 120Hz', prosesor: 'Exynos 1380', ram: '6GB / 8GB', storage: '128GB / 256GB', kamera_utama: '50MP + 8MP + 5MP', baterai: '5,000 mAh', os: 'Android 14 / One UI 6.1', rilis: '2024' } },

  // Xiaomi
  { name: 'Xiaomi 14', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.36" AMOLED 120Hz 1.5K', prosesor: 'Snapdragon 8 Gen 3', ram: '12GB', storage: '256GB / 512GB', kamera_utama: 'Leica 50MP + 50MP Ultra Wide + 50MP 3.2x Tele', kamera_depan: '32MP', baterai: '4,610 mAh', os: 'Android 14 / HyperOS', konektivitas: '5G, Wi-Fi 7', rilis: '2024' } },
  { name: 'Xiaomi 14 Ultra', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.73" AMOLED 120Hz 2K', prosesor: 'Snapdragon 8 Gen 3', ram: '16GB', storage: '512GB / 1TB', kamera_utama: 'Leica 50MP 1" + 50MP Ultra Wide + 50MP 3.2x + 50MP 5x Tele', baterai: '5,000 mAh', os: 'Android 14 / HyperOS', pengisian: '90W kabel + 80W wireless', rilis: '2024' } },
  { name: 'Xiaomi 14T Pro', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.67" AMOLED 144Hz 1.5K', prosesor: 'Snapdragon 8 Gen 3', ram: '12GB / 16GB', storage: '256GB / 512GB', kamera_utama: 'Leica 50MP + 12MP + 50MP 2.6x Tele', baterai: '5,000 mAh', os: 'Android 14 / HyperOS', pengisian: '120W kabel + 50W wireless', rilis: '2024' } },
  { name: 'Xiaomi 15', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.36" AMOLED 120Hz 1.5K', prosesor: 'Snapdragon 8 Elite', ram: '12GB', storage: '256GB / 512GB', kamera_utama: 'Leica 50MP + 50MP Ultra Wide + 50MP 3.2x Tele', baterai: '5,240 mAh', os: 'Android 15 / HyperOS 2', pengisian: '90W kabel + 50W wireless', rilis: '2024' } },
  { name: 'Xiaomi 15 Ultra', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.73" AMOLED 120Hz 2K', prosesor: 'Snapdragon 8 Elite', ram: '16GB', storage: '512GB / 1TB', kamera_utama: 'Leica 50MP 1" + 50MP Ultra Wide + 50MP 3x + 200MP 4.3x Tele', baterai: '5,500 mAh', os: 'Android 15 / HyperOS 2', pengisian: '90W kabel + 80W wireless', rilis: '2025' } },
  { name: 'Redmi Note 14 Pro+', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.67" AMOLED 120Hz 1.5K', prosesor: 'Snapdragon 7s Gen 3', ram: '12GB', storage: '256GB / 512GB', kamera_utama: '200MP + 8MP + 2MP', baterai: '6,067 mAh', os: 'Android 14 / HyperOS', pengisian: '90W', rilis: '2024' } },
  { name: 'Redmi Note 14 Pro', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.67" AMOLED 120Hz 1.5K', prosesor: 'MediaTek Dimensity 7300-Ultra', ram: '8GB / 12GB', storage: '256GB', kamera_utama: '200MP + 8MP + 2MP', kamera_depan: '20MP', baterai: '5,500 mAh', os: 'Android 14 / HyperOS', pengisian: '45W', rilis: '2024' } },
  { name: 'POCO X7 Pro', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.67" AMOLED 120Hz', prosesor: 'MediaTek Dimensity 8400-Ultra', ram: '8GB / 12GB', storage: '256GB', kamera_utama: '50MP + 8MP', baterai: '6,000 mAh', os: 'Android 15 / HyperOS 2', pengisian: '90W', rilis: '2025' } },
  { name: 'POCO F6 Pro', brand: 'Xiaomi', category: 'smartphone' as GadgetCategory, specs: { layar: '6.67" AMOLED 120Hz 2K', prosesor: 'Snapdragon 8 Gen 2', ram: '12GB / 16GB', storage: '256GB / 512GB / 1TB', kamera_utama: '50MP + 8MP + 2MP', baterai: '5,000 mAh', os: 'Android 14 / HyperOS', pengisian: '120W', rilis: '2024' } },

  // OPPO
  { name: 'Find X8 Pro', brand: 'OPPO', category: 'smartphone' as GadgetCategory, specs: { layar: '6.78" AMOLED 120Hz 2K', prosesor: 'Snapdragon 8 Elite', ram: '12GB / 16GB', storage: '256GB / 512GB', kamera_utama: 'Hasselblad 50MP + 50MP Ultra Wide + 50MP 3x + 50MP 6x Tele', baterai: '5,910 mAh', os: 'Android 15 / ColorOS 15', pengisian: '80W kabel + 50W wireless', rilis: '2024' } },
  { name: 'Find X8', brand: 'OPPO', category: 'smartphone' as GadgetCategory, specs: { layar: '6.59" AMOLED 120Hz', prosesor: 'MediaTek Dimensity 9400', ram: '12GB', storage: '256GB / 512GB', kamera_utama: 'Hasselblad 50MP + 50MP Ultra Wide + 50MP 3x Tele', baterai: '5,630 mAh', os: 'Android 15 / ColorOS 15', pengisian: '80W', rilis: '2024' } },
  { name: 'Reno 13 Pro', brand: 'OPPO', category: 'smartphone' as GadgetCategory, specs: { layar: '6.83" AMOLED 120Hz', prosesor: 'MediaTek Dimensity 8350', ram: '12GB', storage: '256GB / 512GB', kamera_utama: '50MP + 50MP Ultra Wide + 50MP 3x Tele', kamera_depan: '50MP', baterai: '5,800 mAh', os: 'Android 15 / ColorOS 15', pengisian: '80W', rilis: '2025' } },
  { name: 'Reno 12 Pro', brand: 'OPPO', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" AMOLED 120Hz', prosesor: 'MediaTek Dimensity 7300-Energy', ram: '12GB', storage: '256GB', kamera_utama: '50MP + 8MP + 50MP 2x Portrait', kamera_depan: '50MP AI', baterai: '5,000 mAh', os: 'Android 14 / ColorOS 14.1', pengisian: '80W', rilis: '2024' } },
  { name: 'A3 Pro 5G', brand: 'OPPO', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" AMOLED 120Hz', prosesor: 'MediaTek Dimensity 7300', ram: '8GB', storage: '256GB', kamera_utama: '50MP + 2MP', baterai: '5,100 mAh', os: 'Android 14 / ColorOS 14.1', pengisian: '45W', rilis: '2024' } },

  // Vivo
  { name: 'X200 Pro', brand: 'Vivo', category: 'smartphone' as GadgetCategory, specs: { layar: '6.78" AMOLED 120Hz 2K', prosesor: 'Snapdragon 8 Elite', ram: '16GB', storage: '512GB / 1TB', kamera_utama: 'ZEISS 50MP 1" + 50MP Ultra Wide + 200MP 4.3x Tele', baterai: '6,000 mAh', os: 'Android 15 / OriginOS 5', pengisian: '90W kabel + 30W wireless', rilis: '2024' } },
  { name: 'X200', brand: 'Vivo', category: 'smartphone' as GadgetCategory, specs: { layar: '6.67" AMOLED 120Hz', prosesor: 'MediaTek Dimensity 9400', ram: '12GB', storage: '256GB / 512GB', kamera_utama: 'ZEISS 50MP + 50MP Ultra Wide + 50MP 3x Tele', baterai: '5,800 mAh', os: 'Android 15 / OriginOS 5', pengisian: '90W', rilis: '2024' } },
  { name: 'V40 Pro', brand: 'Vivo', category: 'smartphone' as GadgetCategory, specs: { layar: '6.78" AMOLED 120Hz 2K', prosesor: 'Snapdragon 8s Gen 3', ram: '12GB', storage: '256GB / 512GB', kamera_utama: 'ZEISS 50MP + 50MP Ultra Wide + 50MP 2x Tele', kamera_depan: '50MP ZEISS', baterai: '5,500 mAh', os: 'Android 14 / Funtouch 14', pengisian: '80W', rilis: '2024' } },
  { name: 'V50', brand: 'Vivo', category: 'smartphone' as GadgetCategory, specs: { layar: '6.77" AMOLED 120Hz', prosesor: 'Snapdragon 7 Gen 3', ram: '8GB / 12GB', storage: '256GB', kamera_utama: 'ZEISS 50MP + 50MP Ultra Wide', kamera_depan: '50MP', baterai: '6,000 mAh', os: 'Android 15 / Funtouch 15', pengisian: '90W', rilis: '2025' } },

  // Google Pixel
  { name: 'Pixel 9', brand: 'Google', category: 'smartphone' as GadgetCategory, specs: { layar: '6.3" OLED 120Hz', prosesor: 'Google Tensor G4', ram: '12GB', storage: '128GB / 256GB', kamera_utama: '50MP + 48MP Ultra Wide', kamera_depan: '10.5MP', baterai: '4,700 mAh', os: 'Android 15', fitur: 'Google AI, 7 tahun update', rilis: '2024' } },
  { name: 'Pixel 9 Pro', brand: 'Google', category: 'smartphone' as GadgetCategory, specs: { layar: '6.3" OLED 120Hz', prosesor: 'Google Tensor G4', ram: '16GB', storage: '128GB / 256GB / 512GB / 1TB', kamera_utama: '50MP + 48MP Ultra Wide + 48MP 5x Tele', baterai: '4,700 mAh', os: 'Android 15', fitur: 'Google AI, 7 tahun update', rilis: '2024' } },
  { name: 'Pixel 9 Pro XL', brand: 'Google', category: 'smartphone' as GadgetCategory, specs: { layar: '6.8" OLED 120Hz', prosesor: 'Google Tensor G4', ram: '16GB', storage: '256GB / 512GB / 1TB', kamera_utama: '50MP + 48MP Ultra Wide + 48MP 5x Tele', baterai: '5,060 mAh', os: 'Android 15', rilis: '2024' } },
  { name: 'Pixel 9a', brand: 'Google', category: 'smartphone' as GadgetCategory, specs: { layar: '6.3" OLED 120Hz', prosesor: 'Google Tensor G4', ram: '8GB', storage: '128GB / 256GB', kamera_utama: '48MP + 13MP Ultra Wide', baterai: '5,100 mAh', os: 'Android 15', fitur: 'Google AI, 7 tahun update', rilis: '2025' } },

  // OnePlus
  { name: 'OnePlus 13', brand: 'OnePlus', category: 'smartphone' as GadgetCategory, specs: { layar: '6.82" AMOLED 120Hz 2K', prosesor: 'Snapdragon 8 Elite', ram: '12GB / 16GB', storage: '256GB / 512GB', kamera_utama: 'Hasselblad 50MP + 50MP Ultra Wide + 50MP 3x Tele', baterai: '6,000 mAh', os: 'Android 15 / OxygenOS 15', pengisian: '100W kabel + 50W wireless', rilis: '2025' } },
  { name: 'OnePlus 13R', brand: 'OnePlus', category: 'smartphone' as GadgetCategory, specs: { layar: '6.78" AMOLED 120Hz', prosesor: 'Snapdragon 8 Gen 3', ram: '8GB / 12GB', storage: '128GB / 256GB', kamera_utama: '50MP + 8MP + 2MP', baterai: '5,500 mAh', os: 'Android 15 / OxygenOS 15', pengisian: '80W', rilis: '2025' } },
  { name: 'OnePlus Open 2', brand: 'OnePlus', category: 'smartphone' as GadgetCategory, specs: { layar_dalam: '8.02" AMOLED 120Hz 2K', layar_luar: '6.31" AMOLED 120Hz', prosesor: 'Snapdragon 8 Elite', ram: '16GB', storage: '512GB', kamera_utama: 'Hasselblad 50MP + 48MP Ultra Wide + 64MP 3x Tele', baterai: '5,600 mAh', pengisian: '67W', rilis: '2025' } },

  // Nothing
  { name: 'Phone (3)', brand: 'Nothing', category: 'smartphone' as GadgetCategory, specs: { layar: '6.67" AMOLED 120Hz', prosesor: 'Snapdragon 8s Gen 4', ram: '12GB', storage: '256GB / 512GB', kamera_utama: '50MP + 50MP Ultra Wide + 50MP Tele', desain: 'Glyph Interface generasi baru', baterai: '5,000 mAh', os: 'Android 15 / Nothing OS 3.0', rilis: '2025' } },
  { name: 'Phone (2a) Plus', brand: 'Nothing', category: 'smartphone' as GadgetCategory, specs: { layar: '6.7" AMOLED 120Hz', prosesor: 'MediaTek Dimensity 7350 Pro', ram: '12GB', storage: '256GB', kamera_utama: '50MP + 50MP Ultra Wide', desain: 'Glyph Interface', baterai: '5,000 mAh', os: 'Android 14 / Nothing OS 2.6', rilis: '2024' } },

  // Realme
  { name: 'GT 7 Pro', brand: 'Realme', category: 'smartphone' as GadgetCategory, specs: { layar: '6.78" AMOLED 120Hz 2K', prosesor: 'Snapdragon 8 Elite', ram: '12GB / 16GB', storage: '256GB / 512GB', kamera_utama: '50MP + 8MP + 50MP 3x Tele', baterai: '6,500 mAh', os: 'Android 15 / Realme UI 6.0', pengisian: '120W', rilis: '2024' } },
  { name: 'GT 6T', brand: 'Realme', category: 'smartphone' as GadgetCategory, specs: { layar: '6.67" AMOLED 120Hz 1.5K', prosesor: 'Snapdragon 7+ Gen 3', ram: '8GB / 12GB', storage: '128GB / 256GB', kamera_utama: '50MP + 8MP', baterai: '5,500 mAh', os: 'Android 14 / Realme UI 5.0', pengisian: '120W', rilis: '2024' } },

  // ─── LAPTOP ───────────────────────────────────────────────────
  { name: 'MacBook Air 13" M3', brand: 'Apple', category: 'laptop' as GadgetCategory, specs: { layar: '13.6" Liquid Retina', prosesor: 'Apple M3 (8-core CPU, 10-core GPU)', ram: '8GB / 16GB / 24GB', storage: '256GB / 512GB / 1TB / 2TB', baterai: '18 jam', os: 'macOS Sequoia', port: '2x Thunderbolt 3, MagSafe, 3.5mm', bobot: '1.24 kg', rilis: '2024' } },
  { name: 'MacBook Air 15" M3', brand: 'Apple', category: 'laptop' as GadgetCategory, specs: { layar: '15.3" Liquid Retina', prosesor: 'Apple M3 (8-core CPU, 10-core GPU)', ram: '8GB / 16GB / 24GB', storage: '256GB / 512GB / 1TB / 2TB', baterai: '18 jam', os: 'macOS Sequoia', bobot: '1.51 kg', rilis: '2024' } },
  { name: 'MacBook Pro 14" M4', brand: 'Apple', category: 'laptop' as GadgetCategory, specs: { layar: '14.2" Liquid Retina XDR ProMotion 120Hz', prosesor: 'Apple M4 (10-core CPU, 10-core GPU)', ram: '16GB / 24GB / 32GB', storage: '512GB / 1TB / 2TB', baterai: '24 jam', os: 'macOS Sequoia', port: '3x Thunderbolt 4, HDMI, SD card, MagSafe', rilis: '2024' } },
  { name: 'MacBook Pro 16" M4 Pro', brand: 'Apple', category: 'laptop' as GadgetCategory, specs: { layar: '16.2" Liquid Retina XDR ProMotion 120Hz', prosesor: 'Apple M4 Pro (14-core CPU, 20-core GPU)', ram: '24GB / 48GB', storage: '512GB / 1TB / 2TB / 4TB', baterai: '24 jam', os: 'macOS Sequoia', port: '3x Thunderbolt 5, HDMI 2.1, SD card, MagSafe', rilis: '2024' } },
  { name: 'MacBook Air 13" M4', brand: 'Apple', category: 'laptop' as GadgetCategory, specs: { layar: '13.6" Liquid Retina', prosesor: 'Apple M4 (10-core CPU, 10-core GPU)', ram: '16GB / 24GB / 32GB', storage: '256GB / 512GB / 1TB / 2TB', baterai: '18 jam', os: 'macOS Sequoia', port: '2x Thunderbolt 4, MagSafe', bobot: '1.24 kg', rilis: '2025' } },
  { name: 'ROG Zephyrus G14 2024', brand: 'ASUS', category: 'laptop' as GadgetCategory, specs: { layar: '14" OLED 2.8K 120Hz', prosesor: 'AMD Ryzen 9 8945HS', gpu: 'NVIDIA GeForce RTX 4070', ram: '32GB LPDDR5X', storage: '1TB NVMe SSD', baterai: '73Wh', os: 'Windows 11', bobot: '1.65 kg', rilis: '2024' } },
  { name: 'ROG Strix SCAR 16 2024', brand: 'ASUS', category: 'laptop' as GadgetCategory, specs: { layar: '16" QHD+ 240Hz', prosesor: 'Intel Core i9-14900HX', gpu: 'NVIDIA GeForce RTX 4090', ram: '32GB DDR5', storage: '2TB NVMe SSD', baterai: '90Wh', os: 'Windows 11', rilis: '2024' } },
  { name: 'VivoBook S 15 OLED', brand: 'ASUS', category: 'laptop' as GadgetCategory, specs: { layar: '15.6" OLED 2.8K 120Hz', prosesor: 'Intel Core Ultra 7 155H', ram: '16GB', storage: '512GB NVMe SSD', baterai: '70Wh', os: 'Windows 11', bobot: '1.7 kg', rilis: '2024' } },
  { name: 'ThinkPad X1 Carbon Gen 12', brand: 'Lenovo', category: 'laptop' as GadgetCategory, specs: { layar: '14" IPS 2.8K 120Hz', prosesor: 'Intel Core Ultra 7 165U', ram: '16GB / 32GB LPDDR5', storage: '512GB / 1TB SSD', baterai: '57Wh', os: 'Windows 11 Pro', bobot: '1.12 kg', rilis: '2024' } },
  { name: 'Legion 5i Gen 9', brand: 'Lenovo', category: 'laptop' as GadgetCategory, specs: { layar: '16" IPS 165Hz', prosesor: 'Intel Core i7-14650HX', gpu: 'NVIDIA GeForce RTX 4060', ram: '16GB DDR5', storage: '512GB SSD', baterai: '80Wh', os: 'Windows 11', rilis: '2024' } },
  { name: 'Yoga 9i Gen 9', brand: 'Lenovo', category: 'laptop' as GadgetCategory, specs: { layar: '14" OLED 2.8K 120Hz Touch', prosesor: 'Intel Core Ultra 7 155H', ram: '16GB LPDDR5X', storage: '1TB SSD', baterai: '75Wh', os: 'Windows 11', bobot: '1.45 kg', rilis: '2024' } },
  { name: 'XPS 13 9340', brand: 'Dell', category: 'laptop' as GadgetCategory, specs: { layar: '13.4" OLED 2.8K 60Hz', prosesor: 'Intel Core Ultra 7 165H', ram: '16GB / 32GB LPDDR5X', storage: '512GB / 1TB SSD', baterai: '55Wh', os: 'Windows 11', bobot: '1.19 kg', rilis: '2024' } },
  { name: 'Spectre x360 14', brand: 'HP', category: 'laptop' as GadgetCategory, specs: { layar: '14" OLED 2.8K 120Hz Touch 2-in-1', prosesor: 'Intel Core Ultra 7 155H', ram: '32GB LPDDR5X', storage: '1TB SSD', baterai: '72Wh', os: 'Windows 11', bobot: '1.41 kg', rilis: '2024' } },
  { name: 'Surface Laptop 6 15"', brand: 'Microsoft', category: 'laptop' as GadgetCategory, specs: { layar: '15" PixelSense 2496x1664 120Hz Touch', prosesor: 'Intel Core Ultra 7 165H', ram: '16GB / 32GB / 64GB', storage: '256GB / 512GB / 1TB SSD', baterai: '54Wh', os: 'Windows 11', bobot: '1.66 kg', rilis: '2024' } },
  { name: 'Galaxy Book 4 Ultra', brand: 'Samsung', category: 'laptop' as GadgetCategory, specs: { layar: '16" Dynamic AMOLED 2X 120Hz 3K', prosesor: 'Intel Core Ultra 9 185H', gpu: 'NVIDIA GeForce RTX 4070', ram: '32GB LPDDR5X', storage: '1TB SSD', baterai: '76Wh', os: 'Windows 11', rilis: '2024' } },

  // ─── TABLET ───────────────────────────────────────────────────
  { name: 'iPad Air 11" M2', brand: 'Apple', category: 'tablet' as GadgetCategory, specs: { layar: '11" Liquid Retina 60Hz', prosesor: 'Apple M2', ram: '8GB', storage: '128GB / 256GB / 512GB / 1TB', kamera_utama: '12MP', kamera_depan: '12MP Ultra Wide landscape', konektivitas: 'Wi-Fi 6E / 5G', os: 'iPadOS 17', rilis: '2024' } },
  { name: 'iPad Air 13" M2', brand: 'Apple', category: 'tablet' as GadgetCategory, specs: { layar: '13" Liquid Retina 60Hz', prosesor: 'Apple M2', ram: '8GB', storage: '128GB / 256GB / 512GB / 1TB', konektivitas: 'Wi-Fi 6E / 5G', os: 'iPadOS 17', rilis: '2024' } },
  { name: 'iPad Pro 11" M4', brand: 'Apple', category: 'tablet' as GadgetCategory, specs: { layar: '11" Ultra Retina XDR OLED Tandem 120Hz', prosesor: 'Apple M4', ram: '8GB / 16GB', storage: '256GB / 512GB / 1TB / 2TB', kamera_utama: '12MP + LiDAR', ketebalan: '5.3mm', os: 'iPadOS 17', rilis: '2024' } },
  { name: 'iPad Pro 13" M4', brand: 'Apple', category: 'tablet' as GadgetCategory, specs: { layar: '13" Ultra Retina XDR OLED Tandem 120Hz', prosesor: 'Apple M4', ram: '8GB / 16GB', storage: '256GB / 512GB / 1TB / 2TB', ketebalan: '5.1mm', os: 'iPadOS 17', rilis: '2024' } },
  { name: 'iPad mini 7', brand: 'Apple', category: 'tablet' as GadgetCategory, specs: { layar: '8.3" Liquid Retina 60Hz', prosesor: 'Apple A17 Pro', ram: '8GB', storage: '128GB / 256GB / 512GB', kamera_utama: '12MP', konektivitas: 'Wi-Fi 6E / 5G', os: 'iPadOS 18', rilis: '2024' } },
  { name: 'Galaxy Tab S10', brand: 'Samsung', category: 'tablet' as GadgetCategory, specs: { layar: '11" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Gen 3', ram: '8GB / 12GB', storage: '128GB / 256GB', kamera_utama: '13MP + 8MP Ultra Wide', os: 'Android 14 / One UI 6.1.1', fitur: 'DeX, S Pen termasuk', rilis: '2024' } },
  { name: 'Galaxy Tab S10+', brand: 'Samsung', category: 'tablet' as GadgetCategory, specs: { layar: '12.4" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Gen 3', ram: '12GB', storage: '256GB / 512GB', os: 'Android 14 / One UI 6.1.1', fitur: 'DeX, S Pen termasuk', rilis: '2024' } },
  { name: 'Galaxy Tab S10 Ultra', brand: 'Samsung', category: 'tablet' as GadgetCategory, specs: { layar: '14.6" Dynamic AMOLED 2X 120Hz', prosesor: 'Snapdragon 8 Gen 3', ram: '12GB / 16GB', storage: '256GB / 512GB / 1TB', os: 'Android 14 / One UI 6.1.1', fitur: 'DeX, S Pen termasuk, dual front camera', rilis: '2024' } },
  { name: 'Xiaomi Pad 7 Pro', brand: 'Xiaomi', category: 'tablet' as GadgetCategory, specs: { layar: '12.1" LCD 2.8K 144Hz', prosesor: 'Snapdragon 8s Gen 3', ram: '8GB / 12GB', storage: '256GB / 512GB', kamera_utama: '50MP', baterai: '10,000 mAh', os: 'Android 15 / HyperOS 2', rilis: '2025' } },

  // ─── WEARABLE ─────────────────────────────────────────────────
  { name: 'Apple Watch Series 10', brand: 'Apple', category: 'wearable' as GadgetCategory, specs: { layar: '46mm / 42mm Always-On LTPO3 OLED', prosesor: 'Apple S10', fitur: 'Sleep apnea detection, ECG, SpO2, GPS', baterai: '18 jam', os: 'watchOS 11', konektivitas: 'Wi-Fi 6, Bluetooth 5.3, LTE', rilis: '2024' } },
  { name: 'Apple Watch Ultra 2', brand: 'Apple', category: 'wearable' as GadgetCategory, specs: { layar: '49mm Always-On LTPO3 OLED', prosesor: 'Apple S9', material: 'Titanium', fitur: 'Dual GPS, Action button, depth gauge, ECG', baterai: '60 jam', os: 'watchOS 11', rilis: '2024' } },
  { name: 'Galaxy Watch 7', brand: 'Samsung', category: 'wearable' as GadgetCategory, specs: { layar: '44mm / 40mm AMOLED', prosesor: 'Exynos W1000', fitur: 'BioActive sensor, ECG, BIA, SpO2, GPS', baterai: '40 jam (44mm)', os: 'Wear OS 5 / One UI 6 Watch', rilis: '2024' } },
  { name: 'Galaxy Watch Ultra', brand: 'Samsung', category: 'wearable' as GadgetCategory, specs: { layar: '47mm AMOLED', material: 'Titanium', fitur: 'Multi-sport GPS, ECG, BIA, SpO2, water resistant 10m', baterai: '48 jam', os: 'Wear OS 5 / One UI 6 Watch', rilis: '2024' } },
  { name: 'Galaxy Ring', brand: 'Samsung', category: 'wearable' as GadgetCategory, specs: { material: 'Titanium', fitur: 'Heart rate, SpO2, sleep tracking, cycle tracking', baterai: '7 hari', bobot: '2.3-3g', kompatibilitas: 'Android 8.0+', ukuran: '5-13', rilis: '2024' } },
  { name: 'Xiaomi Smart Band 9 Pro', brand: 'Xiaomi', category: 'wearable' as GadgetCategory, specs: { layar: '1.74" AMOLED', fitur: 'Heart rate, SpO2, sleep tracking, GPS built-in, 150+ olahraga', baterai: '21 hari', ketahanan: '5ATM waterproof', rilis: '2024' } },
  { name: 'Garmin Fenix 8', brand: 'Garmin', category: 'wearable' as GadgetCategory, specs: { layar: '51mm / 47mm / 43mm AMOLED atau MIP', fitur: 'Multi-band GPS, altimeter, compass, topographic maps, diving', baterai: '29 hari GPS 48 jam', material: 'Titanium / Fiber-reinforced polymer', rilis: '2024' } },
  { name: 'Pixel Watch 3', brand: 'Google', category: 'wearable' as GadgetCategory, specs: { layar: '45mm / 41mm AMOLED', prosesor: 'Snapdragon W5 Gen 1', fitur: 'Heart rate, SpO2, ECG, Sleep coaching, GPS, Fitbit integration', baterai: '24 jam', os: 'Wear OS 4', rilis: '2024' } },

  // ─── AUDIO ────────────────────────────────────────────────────
  { name: 'AirPods 4', brand: 'Apple', category: 'audio' as GadgetCategory, specs: { tipe: 'In-ear open fit TWS', chip: 'Apple H2', fitur: 'Active Noise Cancellation (model ANC), Adaptive Audio, Transparency', baterai_bud: '5 jam (30 jam dengan case)', konektivitas: 'Bluetooth 5.3', rilis: '2024' } },
  { name: 'AirPods Pro 2', brand: 'Apple', category: 'audio' as GadgetCategory, specs: { tipe: 'In-ear TWS', chip: 'Apple H2', fitur: 'Active Noise Cancellation, Adaptive Transparency, Personalized Spatial Audio', baterai_bud: '6 jam ANC (30 jam dengan case)', konektivitas: 'Bluetooth 5.3', rilis: '2023-2024' } },
  { name: 'AirPods Max USB-C', brand: 'Apple', category: 'audio' as GadgetCategory, specs: { tipe: 'Over-ear', chip: 'Apple H1 (dual)', fitur: 'Active Noise Cancellation, Transparency mode, Spatial Audio', baterai: '20 jam ANC', konektivitas: 'Bluetooth 5.0', port: 'USB-C', rilis: '2024' } },
  { name: 'Galaxy Buds 3 Pro', brand: 'Samsung', category: 'audio' as GadgetCategory, specs: { tipe: 'In-ear TWS', fitur: 'Active Noise Cancellation, 360 Audio, SSC Hi-Fi codec', baterai_bud: '6 jam ANC (30 jam dengan case)', konektivitas: 'Bluetooth 5.4, LE Audio', ketahanan: 'IPX7', rilis: '2024' } },
  { name: 'Galaxy Buds 3', brand: 'Samsung', category: 'audio' as GadgetCategory, specs: { tipe: 'In-ear TWS open fit', fitur: 'ANC, 360 Audio', baterai_bud: '6 jam (30 jam dengan case)', konektivitas: 'Bluetooth 5.4', rilis: '2024' } },
  { name: 'WH-1000XM5', brand: 'Sony', category: 'audio' as GadgetCategory, specs: { tipe: 'Over-ear wireless', fitur: '30dB Active Noise Cancellation, LDAC, Speak-to-Chat, Quick Charge', baterai: '30 jam ANC', konektivitas: 'Bluetooth 5.2, NFC', bobot: '250g', rilis: '2022-2024' } },
  { name: 'WH-1000XM6', brand: 'Sony', category: 'audio' as GadgetCategory, specs: { tipe: 'Over-ear wireless', fitur: 'Improved ANC, LDAC, DSEE Extreme, Speak-to-Chat, Quick Charge', baterai: '30 jam ANC', konektivitas: 'Bluetooth 5.3, NFC', bobot: '254g', rilis: '2025' } },
  { name: 'WF-1000XM5', brand: 'Sony', category: 'audio' as GadgetCategory, specs: { tipe: 'In-ear TWS', fitur: 'Active Noise Cancellation, LDAC, DSEE Extreme, Speak-to-Chat', baterai_bud: '8 jam ANC (24 jam dengan case)', konektivitas: 'Bluetooth 5.3', rilis: '2023-2024' } },
  { name: 'QuietComfort Ultra Headphones', brand: 'Bose', category: 'audio' as GadgetCategory, specs: { tipe: 'Over-ear wireless', fitur: 'CustomTune ANC, Immersive Audio, Multi-Point', baterai: '24 jam ANC', konektivitas: 'Bluetooth 5.3', bobot: '246g', rilis: '2024' } },
  { name: 'QuietComfort Ultra Earbuds', brand: 'Bose', category: 'audio' as GadgetCategory, specs: { tipe: 'In-ear TWS', fitur: 'CustomTune ANC, Immersive Audio, Multi-Point', baterai_bud: '6 jam ANC (18 jam dengan case)', ketahanan: 'IPX4', rilis: '2024' } },
  { name: 'Pixel Buds Pro 2', brand: 'Google', category: 'audio' as GadgetCategory, specs: { tipe: 'In-ear TWS', chip: 'Tensor A1', fitur: 'Silent Seal 2.0 ANC, Conversation Detection, Spatial Audio', baterai_bud: '8 jam ANC (30 jam dengan case)', konektivitas: 'Bluetooth 5.4, LE Audio', rilis: '2024' } },
];

async function main() {
  console.log(`🌱 Seeding ${gadgets.length} gadgets...`);
  let success = 0;
  let skipped = 0;

  for (const g of gadgets) {
    try {
      await prisma.gadget.upsert({
        where: { name_brand: { name: g.name, brand: g.brand } },
        update: { specs: g.specs, imageUrl: (g as any).imageUrl ?? null, category: g.category },
        create: {
          name: g.name,
          brand: g.brand,
          category: g.category,
          specs: g.specs,
          imageUrl: (g as any).imageUrl ?? null,
        },
      });
      success++;
      process.stdout.write(`✅ ${g.brand} ${g.name}\n`);
    } catch (e: any) {
      skipped++;
      process.stdout.write(`⚠️  Skip: ${g.brand} ${g.name} — ${e.message}\n`);
    }
  }

  console.log(`\n🎉 Selesai! ${success} berhasil, ${skipped} dilewati.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
